### ISSUE TITLE
Build Error: PhenixSdk.jar error in opening zip file

### ISSUE THREAD

**Issue by hocinehamdi** [PhenixP2P/PCastDemo#1]
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources]
Error:error reading /Users/h_hamdi/Downloads/PCastDemo-master/android/app/libs/PhenixSdk.jar; error in opening zip file
on timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
/Users/h_hamdi/Downloads/PCastDemo-master/android/app/src/main/java/com/phenixp2p/demo/presenters/inter/IMainPresenter.java
Error:(18, 27) error: package com.phenixp2p.pcast does not exist
Error:(21, 23) error: cannot find symbol class Renderer
/Users/h_hamdi/Downloads/PCastDemo-master/android/app/src/main/java/com/phenixp2p/demo/presenters/MainPresenter.java
Error:(20, 27) error: package com.phenixp2p.pcast does not exist
Error:(23, 11) error: cannot find symbol class Renderer
Error:(38, 30) error: cannot find symbol class Renderer
/Users/h_hamdi/Downloads/PCastDemo-master/android/app/src/main/java/com/phenixp2p/demo/ui/view/IMainView.java
Error:(18, 27) error: package com.phenixp2p.pcast does not exist
Error:(21, 19) error: cannot find symbol class Renderer
/Users/h_hamdi/Downloads/PCastDemo-master/android/app/src/main/java/com/phenixp2p/demo/ui/activities/MainActivity.java
Error:(45, 27) error: package com.phenixp2p.pcast does not exist
Error:(46, 27) error: package com.phenixp2p.pcast does not exist
Error:(47, 27) error: package com.phenixp2p.pcast does not exist
Error:(48, 27) error: package com.phenixp2p.pcast does not exist
Error:(49, 27) error: package com.phenixp2p.pcast does not exist
Error:(50, 27) error: package com.phenixp2p.pcast does not exist
Error:(51, 27) error: package com.phenixp2p.pcast does not exist
Error:(52, 27) error: package com.phenixp2p.pcast does not exist
Error:(53, 27) error: package com.phenixp2p.pcast does not exist
Error:(54, 35) error: package com.phenixp2p.pcast.android does not exist
Error:(55, 35) error: package com.phenixp2p.pcast.android does not exist
Error:(72, 11) error: cannot find symbol class PCast
Error:(74, 11) error: cannot find symbol class UserMediaStream
Error:(446, 26) error: cannot find symbol class Renderer
Error:(326, 18) error: cannot find symbol variable AndroidPCastFactory
Error:(327, 31) error: cannot find symbol class PCastInitializeOptions
Error:(328, 52) error: package PCast does not exist
Error:(336, 14) error: package PCast does not exist
Error:(341, 14) error: package PCast does not exist
Error:(350, 5) error: cannot find symbol class UserMediaOptions
Error:(350, 39) error: cannot find symbol class UserMediaOptions
Error:(351, 48) error: cannot find symbol variable FacingMode
Error:(354, 50) error: package PCast does not exist
Error:(373, 82) error: package PCast does not exist
Error:(429, 57) error: package PCast does not exist
Error:(448, 24) error: cannot find symbol class AndroidVideoRenderSurface
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 1.938 secs
Information:35 errors
Information:0 warnings
Information:See complete output in console

**Comment by sempi** [comment]
Thanks @hocinehamdi for offline communication to resolve this issue.

If anyone else is running into similar problems. Make sure to follow the [setup instructions](https://github.com/PhenixP2P/PCastDemo). A short check list:

1. `git-lfs` is properly installed
2. your git ID was granted access to the SDK repositories
3. ssh is correctly configured for usage with git, e.g. `git clone` works from command line
